### ISSUE TITLE
git origin issue in get-icons.js

### ISSUE THREAD

**Issue by vallq** [osrf/romi-dashboard#148]
```
File .resources.json was created successfully.
Reinitialized existing Git repository in /home/valerie/dev/romi_ws/src/romi-dashboard/packages/dashboard/tmp/.git/
fatal: remote origin already exists.
child_process.js:669
    throw err;
    ^
Error: Command failed: git init && git remote add -f origin "https://github.com/osrf/rmf_demos.git"
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at SparseCheckoutGitV217.execute (/home/valerie/dev/romi_ws/src/romi-dashboard/packages/dashboard/scripts/setup/get-icons.js:75:5)
    at /home/valerie/dev/romi_ws/src/romi-dashboard/packages/dashboard/scripts/setup/get-icons.js:114:85
    at ChildProcess.exithandler (child_process.js:294:7)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Pipe.<anonymous> (net.js:674:12) {
  status: 128,
  signal: null,
  output: [ null, null, null ],
  pid: 10127,
  stdout: null,
  stderr: null
}
```
unable to download newly added icons from github on git v2.17.1

**Comment by ChawinTan** [comment]
What is the Repo, Branch and Folder you set? If there is a whitespace behind, it will also fail, although looking at the error this is not likely the case.

**Comment by matiasbavera** [comment]
It's a conflict of names, she already has a remote called origin, we just need to renamed
